server:
  port: 8081
  servlet:
    context-path: /@artifactId@
spring:
  application:
    name: springboot-basedemo
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
